export const CREATE_STUDENT="CREATE_STUDENT";
export const CREATE_STUDENT_PENDING="CREATE_STUDENT_PENDING";
export const CREATE_STUDENT_SUCCESS="CREATE_STUDENT_SUCCESS";
export const CREATE_STUDENT_ERROR="CREATE_STUDENT_ERROR";